services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  backend:
    build:
      context: ./backend
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - db
      - migrate
  celery:
    build:
      context: ./backend
    command: celery -A tasks worker --loglevel=info
    volumes:
      - ./backend:/app
    depends_on:
      - redis
      - db
  celery-beat:
    build:
      context: ./backend
    command: celery -A tasks beat --loglevel=info
    volumes:
      - ./backend:/app
    depends_on:
      - redis
      - db
  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
volumes:
  pgdata: