"""add_chat_title_and_timestamps

Revision ID: fa5b88e69ba5
Revises: bad9b23012e4
Create Date: 2025-06-13 11:47:53.227668

"""
revision = 'fa5b88e69ba5'
down_revision = 'bad9b23012e4'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_sessions', sa.Column('title', sa.String(length=255), nullable=False))
    op.add_column('chat_sessions', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('chat_sessions', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('messages', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('messages', 'content',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_constraint('messages_session_id_fkey', 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'chat_sessions', ['session_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key('messages_session_id_fkey', 'messages', 'chat_sessions', ['session_id'], ['id'])
    op.alter_column('messages', 'content',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('messages', 'created_at')
    op.drop_column('chat_sessions', 'updated_at')
    op.drop_column('chat_sessions', 'created_at')
    op.drop_column('chat_sessions', 'title')
    # ### end Alembic commands ### 