name: Deploy to Droplet

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH key and known_hosts
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass

      - name: Copy files to Droplet
        run: |
          sshpass -p "${{ secrets.DROPLET_PASSWORD }}" scp -o StrictHostKeyChecking=no -r . ${{ secrets.DROPLET_USER }}@${{ secrets.DROPLET_HOST }}:/home/${{ secrets.DROPLET_USER }}/AI-chatbot-tmp

      - name: Deploy on Droplet
        run: |
          sshpass -p "${{ secrets.DROPLET_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.DROPLET_USER }}@${{ secrets.DROPLET_HOST }} "
            rm -rf ~/AI-chatbot-old &&
            mv ~/AI-chatbot ~/AI-chatbot-old 2>/dev/null || true &&
            mv ~/AI-chatbot-tmp ~/AI-chatbot &&
            cd ~/AI-chatbot &&
            docker compose down || true &&
            docker compose up --build -d
          "
